spring.application.name=learn_english_with_ia

# Nom de ta base de données magique en mémoire
spring.datasource.url=jdbc:h2:mem:learn_english_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Demande à Hibernate de générer automatiquement tes tables à partir de tes @Entity
spring.jpa.hibernate.ddl-auto=update

# Affiche en direct les requêtes SQL générées par Spring dans ta console
spring.jpa.show-sql=true
